### ISSUE TITLE
Scriban source include fails with many "is inaccessible due to its protection level" or "is not defined or imported" errors

### ISSUE THREAD

**Issue by RobSmyth** [scriban/scriban#672]
## Describe the bug

When using Scriban 7.1.0 with PackageScribanIncludeSource=true in a netstandard2.0 source generator project, builds fail with multiple "is inaccessible due to its protection level" or "is not defined or imported" errors. 

Builds fine with Scriban 7.0.3.

Some of the compile errors:

```
  ..\.nuget\packages\scriban\7.1.0\src\Scriban\Functions\LiquidBuiltinsFunctions.cs(102,14,102,42): error CS0122: 'UnconditionalSuppressMessageAttribute' is inaccessible due to its protection level
  ...\.nuget\packages\scriban\7.1.0\src\Scriban\Functions\DateTimeFunctions.cs(587,61,587,74): error CS0122: 'UnconditionalSuppressMessageAttribute.Justification' is inaccessible due to its protection level
  ...\.nuget\packages\scriban\7.1.0\src\Scriban\Helpers\ReflectionHelper.cs(38,51,38,77): error CS0122: 'DynamicallyAccessedMembersAttribute' is inaccessible due to its protection level
  ...\.nuget\packages\scriban\7.1.0\src\Scriban\Runtime\Accessors\DictionaryAccessor.cs(32,10,32,29): error CS0122: 'RequiresDynamicCodeAttribute' is inaccessible due to its protection level
  ...\.nuget\packages\scriban\7.1.0\src\Scriban\Runtime\Accessors\DictionaryAccessor.cs(33,10,33,34): error CS0122: 'RequiresUnreferencedCodeAttribute' is inaccessible due to its protection level
  ...\.nuget\packages\scriban\7.1.0\src\Scriban\Runtime\Accessors\DictionaryAccessor.cs(195,18,195,27): error CS0122: 'MaybeNullAttribute' is inaccessible due to its protection level
  ...\.nuget\packages\scriban\7.1.0\src\Scriban\Runtime\ScriptLazy.cs(19,50,19,80): error CS0122: 'DynamicallyAccessedMemberTypes' is inaccessible due to its protection level
  ...\.nuget\packages\scriban\7.1.0\src\Scriban\Runtime\ScriptArray.cs(149,10,149,19): error CS0122: 'AllowNullAttribute' is inaccessible due to its protection level
  ...\.nuget\packages\scriban\7.1.0\src\Scriban\Parsing\ParserOptions.cs(25,48,25,52): error CS0518: Predefined type 'System.Runtime.CompilerServices.IsExternalInit' is not defined or imported
```

> [!Note]
> Similar to #665 but a unable to access instead of duplicates. I'm not referencing Polyfill.

An unexpected consequence of commit 37f226a?

## To Reproduce

Project setup:

* Target framework: netstandard2.0
* Project type: Roslyn source generator
* Scriban: 7.1.0

Relevant csproj configuration:

```xml
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <IsRoslynComponent>true</IsRoslynComponent>
    <PackageScribanIncludeSource>true</PackageScribanIncludeSource>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.3.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.3.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Scriban" Version="7.1.0" IncludeAssets="Build" />
    <PackageReference Include="System.Text.Json" Version="10.0.5" />
  </ItemGroup>
```

Result:

Build fails with dozens of errors (see above).

## Workaround

Roll back to Scriban 7.0.3.

**Comment by xoofx** [comment]
You need to follow the documentation [here](https://github.com/scriban/scriban/blob/master/site/docs/getting-started.md#source-embedding) and add a polyfill assembly for it.

**Comment by RobSmyth** [comment]
Hi @xoofx,

I added pollyfill but the problem persists with Scriban 7.1.0. Works fine with Scriban 7.0.3.

My references are now:

```xml
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.3.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="5.3.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Scriban" Version="7.1.0" IncludeAssets="Build" />
    <PackageReference Include="PolySharp" Version="1.15.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Text.Json" Version="10.0.5" />
```

I did a complete VS reboot to be sure it was loaded.

~~FYI - Possibly unrelated but since updating from Scriban  5.11.0 I've not been able to build the project on my ubuntu build system. It gives an error about the version of the Roslyn compiler (it wants 5.3.0). It has the ver 10 SDK. I'm still investigating that.~~
